name: berte-ai-service
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2 == 1.0.8
  - ca-certificates == 2024.7.2
  - libffi == 3.4.4
  - openssl == 3.0.14
  - python == 3.12.4
  - setuptools == 69.5.1
  - sqlite == 3.45.3
  - tk == 8.6.14
  - wheel == 0.43.0
  - xz == 5.4.6
  - zlib == 1.2.13
  - pip==24.0.0
  - toml == 0.10.2
  - pluggy == 1.0.0
  - colorama == 0.4.6
  - iniconfig == 1.1.1
  - pytest == 7.4.4
  - pytest-cov == 4.1.0
  - coverage == 7.2.2
  - conda-forge:langchain == 0.2.8
  - conda-forge:langchain-community == 0.2.7
  - pip:
      - pydantic == 2.8.2
      - pylint == 3.2.6
      - pydantic-core == 2.20.1
      - tzdata == 2024.1
