name: berte-ai-service
# Set conda config --set channel_priority flexible for your conda env
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bzip2 == 1.0.8
  - ca-certificates == 2024.7.2
  - colorama == 0.4.6
  - coverage == 7.2.2
  - cuda-toolkit==12.4
  - iniconfig == 1.1.1
  - langchain == 0.2.8
  - langchain-community == 0.2.7
  - libffi == 3.4.4
  - openssl == 3.0.14
  - pip==24.0.0
  - pluggy == 1.0.0
  - pytest == 7.4.4
  - pytest-cov == 4.1.0
  - pytest-env == 1.1.3
  - python == 3.12.4
  - pytorch==2.4.0
  - setuptools == 69.5.1
  - sqlite == 3.45.3
  - tk == 8.6.14
  - toml == 0.10.2
  - wheel == 0.43.0
  - xz == 5.4.6
  - zlib == 1.2.13
  - pip:
      - nvidia-cudnn-cu12==9.2.1.18
      - pydantic == 2.8.2
      - pydantic-core == 2.20.1
      - pylint == 3.2.6
      - scipy == 1.14.0
      - transformers == 4.43.3
      - tzdata == 2024.1
