[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[metadata]
name = "src"

[tool.pytest.ini_options]
pythonpath = [".", "src/main/app"]
env = [
    "OLLAMA_HOST = localhost:8080"
]

[tool.coverage.run]
source = ['src']
relative_files = true
omit = ['*test*']
