[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[metadata]
name = "src"

[tool.pytest.ini_options]
pythonpath = [".", "src/main/app"]

[tool.coverage.run]
source = ['src']
relative_files = true
